// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_finite_or_zero
NumericVector cpp_finite_or_zero(NumericVector value);
RcppExport SEXP _blackbird_cpp_finite_or_zero(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_finite_or_zero(value));
    return rcpp_result_gen;
END_RCPP
}
// cpp_finite_or_one
NumericVector cpp_finite_or_one(NumericVector value);
RcppExport SEXP _blackbird_cpp_finite_or_one(SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_finite_or_one(value));
    return rcpp_result_gen;
END_RCPP
}
// getRowNM
NumericVector getRowNM(NumericMatrix x, int y);
RcppExport SEXP _blackbird_getRowNM(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(getRowNM(x, y));
    return rcpp_result_gen;
END_RCPP
}
// getRowIM
IntegerVector getRowIM(IntegerMatrix x, int y);
RcppExport SEXP _blackbird_getRowIM(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(getRowIM(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dropValues
IntegerVector dropValues(IntegerVector x, IntegerVector valuesToRemove);
RcppExport SEXP _blackbird_dropValues(SEXP xSEXP, SEXP valuesToRemoveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type valuesToRemove(valuesToRemoveSEXP);
    rcpp_result_gen = Rcpp::wrap(dropValues(x, valuesToRemove));
    return rcpp_result_gen;
END_RCPP
}
// drop_first
IntegerVector drop_first(IntegerVector x);
RcppExport SEXP _blackbird_drop_first(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(drop_first(x));
    return rcpp_result_gen;
END_RCPP
}
// containsIV
bool containsIV(IntegerVector vec, int value);
RcppExport SEXP _blackbird_containsIV(SEXP vecSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(containsIV(vec, value));
    return rcpp_result_gen;
END_RCPP
}
// getIndicesGreaterThanZero
IntegerVector getIndicesGreaterThanZero(NumericVector vec);
RcppExport SEXP _blackbird_getIndicesGreaterThanZero(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(getIndicesGreaterThanZero(vec));
    return rcpp_result_gen;
END_RCPP
}
// getCommonElements
IntegerVector getCommonElements(IntegerVector vec1, IntegerVector vec2);
RcppExport SEXP _blackbird_getCommonElements(SEXP vec1SEXP, SEXP vec2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type vec1(vec1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vec2(vec2SEXP);
    rcpp_result_gen = Rcpp::wrap(getCommonElements(vec1, vec2));
    return rcpp_result_gen;
END_RCPP
}
// minInt
int minInt(int a, int b);
RcppExport SEXP _blackbird_minInt(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(minInt(a, b));
    return rcpp_result_gen;
END_RCPP
}
// getPositionIV
int getPositionIV(IntegerVector vec, int value);
RcppExport SEXP _blackbird_getPositionIV(SEXP vecSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(getPositionIV(vec, value));
    return rcpp_result_gen;
END_RCPP
}
// getIndicesNotEqual
IntegerVector getIndicesNotEqual(IntegerVector vec, int value);
RcppExport SEXP _blackbird_getIndicesNotEqual(SEXP vecSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type value(valueSEXP);
    rcpp_result_gen = Rcpp::wrap(getIndicesNotEqual(vec, value));
    return rcpp_result_gen;
END_RCPP
}
// sumNumericVectors
NumericVector sumNumericVectors(NumericVector v1, NumericVector v2);
RcppExport SEXP _blackbird_sumNumericVectors(SEXP v1SEXP, SEXP v2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v2(v2SEXP);
    rcpp_result_gen = Rcpp::wrap(sumNumericVectors(v1, v2));
    return rcpp_result_gen;
END_RCPP
}
// storeRowElements
NumericMatrix storeRowElements(NumericMatrix mat, int rowIndex, NumericVector values);
RcppExport SEXP _blackbird_storeRowElements(SEXP matSEXP, SEXP rowIndexSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type rowIndex(rowIndexSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(storeRowElements(mat, rowIndex, values));
    return rcpp_result_gen;
END_RCPP
}
// storeRow
IntegerMatrix storeRow(IntegerMatrix mat, IntegerVector vec, int rowIndex);
RcppExport SEXP _blackbird_storeRow(SEXP matSEXP, SEXP vecSEXP, SEXP rowIndexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type vec(vecSEXP);
    Rcpp::traits::input_parameter< int >::type rowIndex(rowIndexSEXP);
    rcpp_result_gen = Rcpp::wrap(storeRow(mat, vec, rowIndex));
    return rcpp_result_gen;
END_RCPP
}
// cpp_min_elev
NumericVector cpp_min_elev(IntegerVector catchment, NumericVector hand, NumericVector dem, Nullable<IntegerVector> subset);
RcppExport SEXP _blackbird_cpp_min_elev(SEXP catchmentSEXP, SEXP handSEXP, SEXP demSEXP, SEXP subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type catchment(catchmentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hand(handSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dem(demSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type subset(subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_min_elev(catchment, hand, dem, subset));
    return rcpp_result_gen;
END_RCPP
}
// cpp_bed_slope
NumericVector cpp_bed_slope(IntegerVector catchment, NumericVector hand, NumericVector slope, Nullable<IntegerVector> subset);
RcppExport SEXP _blackbird_cpp_bed_slope(SEXP catchmentSEXP, SEXP handSEXP, SEXP slopeSEXP, SEXP subsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type catchment(catchmentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hand(handSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type subset(subsetSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_bed_slope(catchment, hand, slope, subset));
    return rcpp_result_gen;
END_RCPP
}
// cpp_preprocessing_tables_old
void cpp_preprocessing_tables_old(double a, NumericVector reachshp_lens, NumericVector reachshp_lens2, NumericVector seqH, IntegerVector uni, IntegerVector catchment, NumericVector dem, NumericVector reghand, NumericMatrix dhands, NumericVector manningsn, NumericVector reachlength, NumericVector slope, List preprocessing_tables, IntegerVector nodeIDs, String flooded_cell_method, String catchment_conveyance_method, String manning_composite_method, String catchment_integration_method, LogicalVector use_dhand);
RcppExport SEXP _blackbird_cpp_preprocessing_tables_old(SEXP aSEXP, SEXP reachshp_lensSEXP, SEXP reachshp_lens2SEXP, SEXP seqHSEXP, SEXP uniSEXP, SEXP catchmentSEXP, SEXP demSEXP, SEXP reghandSEXP, SEXP dhandsSEXP, SEXP manningsnSEXP, SEXP reachlengthSEXP, SEXP slopeSEXP, SEXP preprocessing_tablesSEXP, SEXP nodeIDsSEXP, SEXP flooded_cell_methodSEXP, SEXP catchment_conveyance_methodSEXP, SEXP manning_composite_methodSEXP, SEXP catchment_integration_methodSEXP, SEXP use_dhandSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type reachshp_lens(reachshp_lensSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type reachshp_lens2(reachshp_lens2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type seqH(seqHSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type uni(uniSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type catchment(catchmentSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dem(demSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type reghand(reghandSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type dhands(dhandsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type manningsn(manningsnSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type reachlength(reachlengthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type slope(slopeSEXP);
    Rcpp::traits::input_parameter< List >::type preprocessing_tables(preprocessing_tablesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nodeIDs(nodeIDsSEXP);
    Rcpp::traits::input_parameter< String >::type flooded_cell_method(flooded_cell_methodSEXP);
    Rcpp::traits::input_parameter< String >::type catchment_conveyance_method(catchment_conveyance_methodSEXP);
    Rcpp::traits::input_parameter< String >::type manning_composite_method(manning_composite_methodSEXP);
    Rcpp::traits::input_parameter< String >::type catchment_integration_method(catchment_integration_methodSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type use_dhand(use_dhandSEXP);
    cpp_preprocessing_tables_old(a, reachshp_lens, reachshp_lens2, seqH, uni, catchment, dem, reghand, dhands, manningsn, reachlength, slope, preprocessing_tables, nodeIDs, flooded_cell_method, catchment_conveyance_method, manning_composite_method, catchment_integration_method, use_dhand);
    return R_NilValue;
END_RCPP
}
// cpp_postprocess_depth
NumericMatrix cpp_postprocess_depth(String postproc_method, NumericMatrix hand, Nullable<NumericMatrix> catchmentdepth_, Nullable<IntegerMatrix> handid_, Nullable<DataFrame> spp_);
RcppExport SEXP _blackbird_cpp_postprocess_depth(SEXP postproc_methodSEXP, SEXP handSEXP, SEXP catchmentdepth_SEXP, SEXP handid_SEXP, SEXP spp_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type postproc_method(postproc_methodSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type hand(handSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type catchmentdepth_(catchmentdepth_SEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerMatrix> >::type handid_(handid_SEXP);
    Rcpp::traits::input_parameter< Nullable<DataFrame> >::type spp_(spp_SEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_postprocess_depth(postproc_method, hand, catchmentdepth_, handid_, spp_));
    return rcpp_result_gen;
END_RCPP
}
// cpp_hand_calc
double cpp_hand_calc(NumericVector x, NumericVector d);
RcppExport SEXP _blackbird_cpp_hand_calc(SEXP xSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_hand_calc(x, d));
    return rcpp_result_gen;
END_RCPP
}
// cpp_postprocess_hand_vector
void cpp_postprocess_hand_vector(NumericVector depth_raster_mm, IntegerVector spp_pointid, NumericVector spp_depth, IntegerVector handid_mm, NumericVector hand_mm);
RcppExport SEXP _blackbird_cpp_postprocess_hand_vector(SEXP depth_raster_mmSEXP, SEXP spp_pointidSEXP, SEXP spp_depthSEXP, SEXP handid_mmSEXP, SEXP hand_mmSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type depth_raster_mm(depth_raster_mmSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type spp_pointid(spp_pointidSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spp_depth(spp_depthSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type handid_mm(handid_mmSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hand_mm(hand_mmSEXP);
    cpp_postprocess_hand_vector(depth_raster_mm, spp_pointid, spp_depth, handid_mm, hand_mm);
    return R_NilValue;
END_RCPP
}
// cpp_downslope_processing
IntegerMatrix cpp_downslope_processing(IntegerVector allcells2eval, IntegerVector validcells, NumericVector emptydem, IntegerVector rpp, NumericVector dinf, NumericMatrix allds, IntegerMatrix alldsind, IntegerMatrix alldirs, int maxiter, int maxcolsize);
RcppExport SEXP _blackbird_cpp_downslope_processing(SEXP allcells2evalSEXP, SEXP validcellsSEXP, SEXP emptydemSEXP, SEXP rppSEXP, SEXP dinfSEXP, SEXP alldsSEXP, SEXP alldsindSEXP, SEXP alldirsSEXP, SEXP maxiterSEXP, SEXP maxcolsizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type allcells2eval(allcells2evalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type validcells(validcellsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type emptydem(emptydemSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type rpp(rppSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dinf(dinfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type allds(alldsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type alldsind(alldsindSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type alldirs(alldirsSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< int >::type maxcolsize(maxcolsizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_downslope_processing(allcells2eval, validcells, emptydem, rpp, dinf, allds, alldsind, alldirs, maxiter, maxcolsize));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_blackbird_cpp_finite_or_zero", (DL_FUNC) &_blackbird_cpp_finite_or_zero, 1},
    {"_blackbird_cpp_finite_or_one", (DL_FUNC) &_blackbird_cpp_finite_or_one, 1},
    {"_blackbird_getRowNM", (DL_FUNC) &_blackbird_getRowNM, 2},
    {"_blackbird_getRowIM", (DL_FUNC) &_blackbird_getRowIM, 2},
    {"_blackbird_dropValues", (DL_FUNC) &_blackbird_dropValues, 2},
    {"_blackbird_drop_first", (DL_FUNC) &_blackbird_drop_first, 1},
    {"_blackbird_containsIV", (DL_FUNC) &_blackbird_containsIV, 2},
    {"_blackbird_getIndicesGreaterThanZero", (DL_FUNC) &_blackbird_getIndicesGreaterThanZero, 1},
    {"_blackbird_getCommonElements", (DL_FUNC) &_blackbird_getCommonElements, 2},
    {"_blackbird_minInt", (DL_FUNC) &_blackbird_minInt, 2},
    {"_blackbird_getPositionIV", (DL_FUNC) &_blackbird_getPositionIV, 2},
    {"_blackbird_getIndicesNotEqual", (DL_FUNC) &_blackbird_getIndicesNotEqual, 2},
    {"_blackbird_sumNumericVectors", (DL_FUNC) &_blackbird_sumNumericVectors, 2},
    {"_blackbird_storeRowElements", (DL_FUNC) &_blackbird_storeRowElements, 3},
    {"_blackbird_storeRow", (DL_FUNC) &_blackbird_storeRow, 3},
    {"_blackbird_cpp_min_elev", (DL_FUNC) &_blackbird_cpp_min_elev, 4},
    {"_blackbird_cpp_bed_slope", (DL_FUNC) &_blackbird_cpp_bed_slope, 4},
    {"_blackbird_cpp_preprocessing_tables_old", (DL_FUNC) &_blackbird_cpp_preprocessing_tables_old, 19},
    {"_blackbird_cpp_postprocess_depth", (DL_FUNC) &_blackbird_cpp_postprocess_depth, 5},
    {"_blackbird_cpp_hand_calc", (DL_FUNC) &_blackbird_cpp_hand_calc, 2},
    {"_blackbird_cpp_postprocess_hand_vector", (DL_FUNC) &_blackbird_cpp_postprocess_hand_vector, 5},
    {"_blackbird_cpp_downslope_processing", (DL_FUNC) &_blackbird_cpp_downslope_processing, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_blackbird(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
