#' @title Generates a boundary condition class object based on the geometry
#'
#' @description
#' Performs numerous checks and processing steps on a Digital Elevation Model (DEM), then saves it.
#'
#' @param geometry a geometry (bb_geometry) class object generated by \code{bb_geometry$new}
#' @param method the method to apply, one of "subcritical", "supercritical", or "mixed" (only subcritical currently supported)
#'
#' @return \item{bc}{object of class bc (boundary condition) configured for the supplied geometry}
#
#' @details
#'
#'
#' @examples
#' print("to do") # xxx
#'
#'
#' @export bb_preprocess_default_boundarycondition
bb_preprocess_default_boundarycondition <- function(geometry=NULL, reachname="default_reach_name",method="subcritical") {

  ## xxx TO DO - add option for using downstream Sf as slope in normal depth

  if (is.null(geometry)) {stop("geometry is required")}
  if ("bb_geometry" %notin% class(geometry)) {stop("geometry must be of class bb_geometry (created by bb_geometry$new())")}
  if (method != "subcritical") {stop("Only the subcritical method is currently supported")}

  default_slope <- 0.01

  if (method == "subcritical") {
    streamnodedf <- geometry$get_streamnodeList_as_dataframe()
    streamnode_bc <- streamnodedf[streamnodedf$downnodeID == -1,]

    # check that node has no ds_reach_length
    # if (streamnode_bc$ds_reach_length != -99) {
    #   warning(sprintf("Likely error in selecting streamnode %s as downstream streamnode, ds_reach_length is not -99",
    #                   streamnode_bc$stationname))
    # }

    bclist <- list(bb_boundarycondition())

    i <- 1
    bc <-  bb_boundarycondition(nodeID=streamnode_bc$nodeID[i],
                                station=streamnode_bc$station[i],
                                stationname=streamnode_bc$stationname[i],
                                reach=reachname,location="downstream",
                                bctype="normal_depth", bcvalue=default_slope)
    bclist[[1]] <- bc

    if (nrow(streamnode_bc)>=2) {
      for (i in 2:nrow(streamnode_bc)) {
        bc <-  bb_boundarycondition(nodeID=streamnode_bc$nodeID[i],
                                    station=streamnode_bc$station[i],
                                    stationname=streamnode_bc$stationname[i],
                                    reach=reachname,location="downstream",
                                    bctype="normal_depth", bcvalue=default_slope)
        bclist <- append(bclist,bc)
      }
    }

  }

  result <- bb_boundaryconditionlist(bclist=bclist)
  return(result)
}
