# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Utility function to extract row from NumericMatrix
NULL

#' Slope of a set of catchments
NULL

#' Postprocesses depths using different methods.
NULL

#' Returns value if finite, 0 if not
#' @param value The value to be considered.
#' @return value if finite, 0 if not.
#' @noRd
cpp_finite_or_zero <- function(value) {
    .Call(`_blackbird_cpp_finite_or_zero`, value)
}

#' Returns value if finite, 1 if not
#' @param value The value to be considered.
#' @return value if finite, 1 if not.
#' @noRd
cpp_finite_or_one <- function(value) {
    .Call(`_blackbird_cpp_finite_or_one`, value)
}

getRowNM <- function(x, y) {
    .Call(`_blackbird_getRowNM`, x, y)
}

#' Utility function to extract row from IntegerMatrix
#' @param x IntegerMatrix
#' @param y indicating yth row to extract
#' @return IntegerVector of the yth row
#' @noRd
getRowIM <- function(x, y) {
    .Call(`_blackbird_getRowIM`, x, y)
}

dropValues <- function(x, valuesToRemove) {
    .Call(`_blackbird_dropValues`, x, valuesToRemove)
}

drop_first <- function(x) {
    .Call(`_blackbird_drop_first`, x)
}

containsIV <- function(vec, value) {
    .Call(`_blackbird_containsIV`, vec, value)
}

getIndicesGreaterThanZero <- function(vec) {
    .Call(`_blackbird_getIndicesGreaterThanZero`, vec)
}

getCommonElements <- function(vec1, vec2) {
    .Call(`_blackbird_getCommonElements`, vec1, vec2)
}

minInt <- function(a, b) {
    .Call(`_blackbird_minInt`, a, b)
}

getPositionIV <- function(vec, value) {
    .Call(`_blackbird_getPositionIV`, vec, value)
}

getIndicesNotEqual <- function(vec, value) {
    .Call(`_blackbird_getIndicesNotEqual`, vec, value)
}

sumNumericVectors <- function(v1, v2) {
    .Call(`_blackbird_sumNumericVectors`, v1, v2)
}

storeRowElements <- function(mat, rowIndex, values) {
    .Call(`_blackbird_storeRowElements`, mat, rowIndex, values)
}

storeRow <- function(mat, vec, rowIndex) {
    .Call(`_blackbird_storeRow`, mat, vec, rowIndex)
}

#' Minimum elevation of a set of catchments
#' @param catchment The matrix form of a catchment raster.
#' @param hand The matrix form of a hand raster.
#' @param dem The matrix form of a dem raster.
#' @param subset A subset of catchment nodeIDs to calculate for (nullable).
#' @return A named vector of catchment minimum elevations.
#' @noRd
cpp_min_elev <- function(catchment, hand, dem, subset) {
    .Call(`_blackbird_cpp_min_elev`, catchment, hand, dem, subset)
}

cpp_bed_slope <- function(catchment, hand, slope, subset) {
    .Call(`_blackbird_cpp_bed_slope`, catchment, hand, slope, subset)
}

#' Preprocessing tables of a set of catchments
#' @param a The dimensions of the dem.
#' @param reachshp_lens An array of lengths of the reach shape object.
#' @param seqH An array of heights to be processed.
#' @param uni An array of unique catchments to process.
#' @param catchment The matrix form of a catchment raster.
#' @param dem The matrix form of a dem raster.
#' @param reghand The matrix form of a regular hand raster.
#' @param dhands The DataFrame of interpolated hand matrices.
#' @param manningsn The matrix form of a manningsn raster.
#' @param reachlength The matrix form of a reachlength raster.
#' @param slope The matrix form of a slope raster.
#' @param preprocessing_tables A list of existing preprocessing tables.
#' @param nodeIDs An array of nodeIDs corresponding to each entry of preprocessing_tables.
#' @param catchment_conveyance_method String containing the catchment conveyance method to be used.
#' @param manning_composite_method String containing the manning composite method to be used.
#' @param catchment_integration_method String containing the method for catchment integration (reach length or Leff).
#' @param use_dhand Logical whether to use DHAND (otherwise uses HAND).
#'
#' @return A list of updated preprocessing tables.
#' @noRd
cpp_preprocessing_tables_old <- function(a, reachshp_lens, reachshp_lens2, seqH, uni, catchment, dem, reghand, dhands, manningsn, reachlength, slope, preprocessing_tables, nodeIDs, flooded_cell_method, catchment_conveyance_method, manning_composite_method, catchment_integration_method, use_dhand) {
    invisible(.Call(`_blackbird_cpp_preprocessing_tables_old`, a, reachshp_lens, reachshp_lens2, seqH, uni, catchment, dem, reghand, dhands, manningsn, reachlength, slope, preprocessing_tables, nodeIDs, flooded_cell_method, catchment_conveyance_method, manning_composite_method, catchment_integration_method, use_dhand))
}

cpp_postprocess_depth <- function(postproc_method, hand, catchmentdepth_ = NULL, handid_ = NULL, spp_ = NULL) {
    .Call(`_blackbird_cpp_postprocess_depth`, postproc_method, hand, catchmentdepth_, handid_, spp_)
}

#' Postprocesing a hand vector of values for depths
#' @param x A single hand (or dhand) value.
#' @param d A single value of depth.
#'
#' @return A list of updated preprocessing tables.
#' @noRd
cpp_hand_calc <- function(x, d) {
    .Call(`_blackbird_cpp_hand_calc`, x, d)
}

#' Postprocesing a hand vector of values for depths
#' @param a The dimensions of the dem.
#' @param reachshp_lens An array of lengths of the reach shape object.
#' @param seqH An array of heights to be processed.
#' @param uni An array of unique catchments to process.
#' @param catchment The matrix form of a catchment raster.
#'
#' @return A list of updated preprocessing tables.
#' @noRd
cpp_postprocess_hand_vector <- function(depth_raster_mm, spp_pointid, spp_depth, handid_mm, hand_mm) {
    invisible(.Call(`_blackbird_cpp_postprocess_hand_vector`, depth_raster_mm, spp_pointid, spp_depth, handid_mm, hand_mm))
}

#' Processing for downslope Dinf method for fuzzy hand
#' @param manningsn The matrix form of a manningsn raster.
#' @return NumericMatrix of pour point IDs for each row of allcells2eval
#' @noRd
cpp_downslope_processing <- function(allcells2eval, validcells, emptydem, rpp, dinf, allds, alldsind, alldirs, maxiter, maxcolsize) {
    .Call(`_blackbird_cpp_downslope_processing`, allcells2eval, validcells, emptydem, rpp, dinf, allds, alldsind, alldirs, maxiter, maxcolsize)
}

